### ISSUE TITLE
0.8.1

### ISSUE THREAD

**Issue by to266** [hyperspy/hyperspy-bundle#1]
It seems the current winpython (2.7.10.1, [link](https://github.com/winpython/winpython/releases/tag/1.2.20150628b) ) does not have a `numpy-MKL` package.

I would also like to include `seaborn` (in addition to just normal `numpy` instead of the not-included MKL version).

There is `numba` available as well, so we can consider that, even though we don't use it

**Comment by francisco-dlp** [comment]
> It seems the current winpython (2.7.10.1, link ) does not have a
> numpy-MKL package.
Are you sure? See this: 
https://github.com/winpython/winpython/wiki/PackageIndex_27
> 
> 
> 
> I would also like to include > seaborn>  (in addition to just normal > numpy>  instead of the not-included MKL version).
+1 for seaborn
> 
> 
> 
> There is > numba>  available as well, so we can consider that, even though we don't use it
+1 for numba

**Comment by to266** [comment]
Well, there is definitely no package named `numpy-MKL` - just the default numpy they supply (apparently) has MKL, so that is not an issue. The bundle, though, still needs changing

**Comment by to266** [comment]
I added those in https://github.com/hyperspy/hyperspy-bundle/commit/30a056bd48808a26cdc4db80090105cf9006274e
