### ISSUE TITLE
HyperSpy Bundle 2018.09.04: HyperSpyUI is not opening

### ISSUE THREAD

**Issue by MGRashed** [hyperspy/hyperspy-bundle#31]
As reported in the gitter room: HyperSpy UI, Jupyter notebook and Spyder IDE are not opening (command prompt exits abruptly). The system is Windows 7 x64.

**Comment by ericpre** [comment]
- HyperSpyUI:  fixed in https://github.com/hyperspy/hyperspy/issues/2066
- Jupyter Notebook and Spyder IDE: I have just tried with a clean install and they both work fine. Can someone reproduce?

**Comment by ericpre** [comment]
@MGRashed: have you tried from a clean install?

**Comment by MGRashed** [comment]
Did a clean install in a new PC (Win 7 x64) and everything worked except HyperSpyUI. I think a new release is needed based on [https://github.com/hyperspy/hyperspy/issues/2066]

**Comment by ericpre** [comment]
Sure, there is no doubt about this but https://github.com/hyperspy/hyperspy/pull/2065 needs to be merged before a new release.
