### ISSUE TITLE
How many python version should be bundle?

### ISSUE THREAD

**Issue by ericpre** [hyperspy/hyperspy-bundle#32]
At IMC in Sydney, @mwalls asked if there was a reason to make bundle for different python version, because for the neophyte, it was not clear which one to use. I believe that currently we have bundles for python 3.5 and python 3.6 because this is just how it happen: when python 3.6 was supported, a python 3.6 bundle have been added and we kept python 3.5.

Since I don't see any particular reason for that, I would suggest to support only one python version.

With the upcoming python 3.7, we could think of keeping python 3.6 until we are sure that python 3.7 is working perfectly fine, along with appropriate explanation that the python 3.7 based bundle is new and that it may have some bugs.

**Comment by francisco-dlp** [comment]
Good point. I fully agree, reducing the choice to just 1 makes the installation and maintenance easier without losing anything AFAICT.

**Comment by ericpre** [comment]
Closing this, since the description of the last release explains the difference between the and the filename have been simplified to have less confusing digits: `py3.6.3` replaced by `py36`, for example.
Keeping two python versions for the [current release](https://github.com/hyperspy/hyperspy-bundle/releases/tag/2018.10.27) (python 3.6 and python 3.7) but when we will confident that the new python version works fine, we should drop the old one.
